[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
duration = 0


[terminal.shell]
program = '/usr/bin/zsh'
args = ['-l', '-c', 'zellij attach || zellij']

[colors.cursor]
text = "CellBackground"


[window]
decorations = "full"
dynamic_padding = false
opacity = 1

[window.padding]
x = 5
y = 5


[font]
size = 14.0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/everblush.toml"]

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"

[terminal]
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"
